apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eduai.fullname" . }}-backend-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eduai.labels" . | nindent 4 }}
automountServiceAccountToken: false
